### ISSUE TITLE
Deno task to create test does not recognises new folder created

### ISSUE THREAD

**Issue by yasserfaraazkhan** [mattermost/mattermost-test-management#2]
Steps:
- run `deno task create-template`
- enter `test-cases/cloud`
- type `y` and create a `new folder` when its asked to create a new-folder 
=> verify successful creation the folder and test
- run `deno task create-template` again
- enter test path as `test-cases/cloud/new-folder`

the Deno task fails to recognise the new-folder `test-cases/cloud/new-folder` and throws error.

**Comment by saturninoabril** [comment]
Thanks @yasserfaraazkhan for filing the issue!

**Comment by saturninoabril** [comment]
@yasserfaraazkhan This should now be fixed when running `deno task validate`. Let me know if it works for you.
