### ISSUE TITLE
bug: broken web application (/www folder) in Gitpod

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-test-management#32]
Broken web application (/www folder) in Gitpod

With error log:
```
Listening on http://localhost:8000/
An error occurred during route handling or page rendering. NotFound: No such file or directory (os error 2)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:56:20)
    at async GET (file:///workspace/mattermost-test-management/www/routes/test-cases/[...slug].tsx:58:25)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:228:22
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:298:18)
```

<img width="963" alt="Screenshot 2022-12-02 at 8 04 42 PM" src="https://user-images.githubusercontent.com/5334504/205289422-3f576dca-d015-4507-856f-dcd4f500a6e8.png">

Thanks @simcard0000 for reporting the issue!

**Comment by simcard0000** [comment]
@saturninoabril I think we're good to close this issue because https://github.com/mattermost/mattermost-test-management/pull/34 got merged in.
